spring.application.name=FitBox

# SQL Server Configuration

spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.jcgbmdxecmtzbefcpzjd&password=261108Mm##mM

spring.datasource.username=postgres.jcgbmdxecmtzbefcpzjd
spring.datasource.password=261108Mm##mM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JWT (JSON Web Token) https://key-generator.com/

application.security.jwt.secret-key=sk-3UXOapTi3A7OW4txsrTgabdjLVKWpksHZXycw6EYI2N6kFqc
application.secutiry.jwt.token-expiration=86400000
application.secutiry.jwt.refresh-token-expiration=604800000

# 86400000 1 dia em milisegundos
# 604800000 7 dias em milisegundos

# CORS
app.cors-enabled=true

# Informa��es

# spring.jpa.hibernate.ddl-auto=
# none: Banco de dados e tabelas devem ser criados com anteced�ncia
# update: Banco de dados deve ser criado com anteced�ncia, tabelas podem ser criadas com anteced�ncia, entretanto,
#         as tabelas ser�o atualizadas pelo c�digo JPA (model)
# create-drop: Banco de dados deve ser criado com anteced�ncia, as tabelas s�o criadas automaticamente pelo c�digo (model),
#              entretanto, as tabelas ser�o exclu�das toda vez que o servidor � interrompido
# create: Banco de dados deve ser criado com anteced�ncia, quando o servidor carrega as tabelas s�o recriadas, entretanto,
#         quando o servidor � interrompido as tabelas permanecem
